'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Backup

    '''<summary>
    '''BackUp_10002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackUp_10002 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BackupBtn_10104 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackupBtn_10104 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BackupText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackupText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BackupLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackupLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Restore_33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Restore_33 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RestoreBtn_33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RestoreBtn_33 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RestoreText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RestoreText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RestoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RestoreLabel As Global.System.Web.UI.WebControls.Label
End Class
