'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EdicionMaterial

    '''<summary>
    '''nav_10123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nav_10123 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitulo_10123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo_10123 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''detalle_132 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents detalle_132 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDetalle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''contenido_705 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contenido_705 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''areaContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaContenido As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''pdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pdf As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pdfUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pdfUpload As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''RegularExpressionValidator2_90048 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator2_90048 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''validadorSize_90048 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validadorSize_90048 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''link_181 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_181 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLink As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tipo_162 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tipo_162 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''comboTipos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comboTipos As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''fLimite_165 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fLimite_165 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFechaMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaMax As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCrear_32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCrear_32 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnActualizar_405 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActualizar_405 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMensajes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''GridView1_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1_ As Global.System.Web.UI.WebControls.GridView
End Class
