'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Inscripcion

    '''<summary>
    '''navCatalogo_50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navCatalogo_50 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nav_57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nav_57 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitulo_124 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo_124 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nombre_11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombre_11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView1_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1_ As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''precio_41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents precio_41 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrecio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrecio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''formadePago_121 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formadePago_121 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''formaDePagoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formaDePagoList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''comboNotasCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comboNotasCredito As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''notaCreditoEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notaCreditoEstado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelTarjeta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''inputTipoTarjetaHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputTipoTarjetaHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''inputNumeroTarjetaHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputNumeroTarjetaHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''inputNombreTarjetaHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputNombreTarjetaHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''inputVtoTarjetaHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputVtoTarjetaHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''inputCodTarjetaHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputCodTarjetaHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''numeroTarjeta_126 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numeroTarjeta_126 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nombreTarjeta_127 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreTarjeta_127 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fechaVtoTarjeta_128 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fechaVtoTarjeta_128 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''codigoTarjeta_129 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents codigoTarjeta_129 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''guardarTarjeta_143 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guardarTarjeta_143 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbxGuardarTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxGuardarTarjeta As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''inscribirse_118 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inscribirse_118 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMensajes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajes As Global.System.Web.UI.WebControls.Label
End Class
