'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Encuestas

    '''<summary>
    '''navEncuestas_52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navEncuestas_52 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''titleEncuestas_52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents titleEncuestas_52 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''encuestaInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents encuestaInicio As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Resultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Resultado As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''encuestaCierre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents encuestaCierre As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMensajes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajes As Global.System.Web.UI.WebControls.Label
End Class
