'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

    '''<summary>
    '''introCultivos_83 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents introCultivos_83 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''preparacion_84 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents preparacion_84 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''cultivos_85 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cultivos_85 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''cultivosAvanzados_86 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cultivosAvanzados_86 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''introHidroponia_87 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents introHidroponia_87 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''cuidado_88 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cuidado_88 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''granEscala_89 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents granEscala_89 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''prepEstrategia_90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prepEstrategia_90 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''masinfo0_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo0_82 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''masinfo1_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo1_82 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''masinfo2_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo2_82 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''masinfo3_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo3_82 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''etapas_91 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etapas_91 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''etapasDetalle_95 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents etapasDetalle_95 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''masinfo4_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo4_82 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''aprenda_92 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aprenda_92 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''aprendaDetalle_96 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aprendaDetalle_96 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''masinfo5_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo5_82 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cree_93 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cree_93 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''creeDetalle_97 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents creeDetalle_97 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''masinfo6_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo6_82 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ventajas_94 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ventajas_94 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ventajasDetalle_98 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ventajasDetalle_98 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''masinfo7_82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents masinfo7_82 As Global.System.Web.UI.WebControls.Label
End Class
