'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RecuperarClave

    '''<summary>
    '''navRecuperarclave_491 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navRecuperarclave_491 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''recuperarclave_491 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recuperarclave_491 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsername_23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsername_23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''usuarioRecuperar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuarioRecuperar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldUser_23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldUser_23 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblEmail_109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail_109 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''emailRecuperar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailRecuperar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldEmail_109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldEmail_109 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''regVldEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVldEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnRecuperar_490 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRecuperar_490 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''yaesusuario_61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yaesusuario_61 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''login_500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents login_500 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Resultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Resultado As Global.System.Web.UI.WebControls.Label
End Class
