'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registracion

    '''<summary>
    '''navRegistro_60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navRegistro_60 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''registro_60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents registro_60 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nombreNuevo_22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreNuevo_22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nombreNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nombreNuevo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldNombre_22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldNombre_22 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''apellidoNuevo_21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apellidoNuevo_21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''apellidoNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apellidoNuevo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldApellido_21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldApellido_21 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblUsername_23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsername_23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''usuarioNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usuarioNuevo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldUsername_23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldUsername_23 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvldUser_23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvldUser_23 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblEmail_109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail_109 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''emailNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailNuevo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldEmail_109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldEmail_109 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''regVldEmail_158 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVldEmail_158 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblPassword_27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPassword_27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''passwordNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwordNuevo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldPass_27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldPass_27 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvldPass_27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvldPass_27 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblConfirmPassword_28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmPassword_28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''passwordRepetidoNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwordRepetidoNuevo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vldConfirmPass_28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldConfirmPass_28 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''vldPasswordMatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldPasswordMatch As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''cbxTerminos_155 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxTerminos_155 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblTerminos_154 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminos_154 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYLas_156 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYLas_156 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPoliticas_152 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPoliticas_152 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vldCbxTerminos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vldCbxTerminos As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnRegistrar_480 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrar_480 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''yaesusuario_61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yaesusuario_61 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''login_500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents login_500 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Resultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Resultado As Global.System.Web.UI.WebControls.Label
End Class
