'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Base

    '''<summary>
    '''headBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headBase As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''HeadBaseContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadBaseContenido As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''formBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formBase As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''HeadLoginView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadLoginView As Global.System.Web.UI.WebControls.LoginView

    '''<summary>
    '''idiomas_29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idiomas_29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''comboIdiomas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comboIdiomas As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''home_3001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents home_3001 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''carreras_3003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents carreras_3003 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''comparacion_51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comparacion_51 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BodyBaseContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BodyBaseContenido As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
