'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MenuBase

    '''<summary>
    '''HeadBaseContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadBaseContenido As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''DetalleNavegacionContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetalleNavegacionContenido As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''BodyMenuContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BodyMenuContenido As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''SideNavigationMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SideNavigationMenu As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''TopNavigationMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TopNavigationMenu As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''BajoMenuContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BajoMenuContenido As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
